"""add is_featured to projects and testimonials

Revision ID: 2b1db5ebe3e0
Revises: b02f146356c4
Create Date: 2026-02-22 21:53:14.045604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1db5ebe3e0'
down_revision: Union[str, None] = 'b02f146356c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('testimonials', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'is_featured')
    op.drop_column('projects', 'is_featured')
    # ### end Alembic commands ###